// src/App.jsx
{
  /* <template>
  <div>
    <hss-modal
      v-model="visible"
      title="tip"
      cancelText="no"
      confirmText="ok"
      :mask="true"
      :maskClosable="true"
      @on-cancel="cancelClick"
      @on-confirm="confirmClick"
      @on-close="closeClick"
      @visible-change="visibleChange"
    >
      <!-- <div slot="foot" slot-scope="aaa">
        <span>自定义foot{{aaa}}</span>
      </div> -->
      hello world
    </hss-modal>

    <span @click="changeModal">点击显示modal</span>
  </div>
</template> */
}

import HssModal from "./components/hss-ui-cpt/modal/index.jsx";
export default {
  components: {
    HssModal,
  },
  data() {
    return {
      visible: false,
    };
  },
  render() {
    return (
      <div>
        <hss-modal
          vModel={this.visible}
          title="tip"
          cancelText="no"
          confirmText="ok"
          mask={true}
          maskClosable={false}
          on-on-cancel={this.cancelClick}
          vOn:on-confirm={this.confirmClick}
          vOn:on-close={this.closeClick}
          vOn:visible-change={this.visibleChange}
          // {...{
          //   scopedSlots: {
          //     foot: (props) => {
          //       return (
          //         <div>
          //           <span>自定义foot,{props.cancelText}</span>
          //           {/* <span>自定义foot,{JSON.stringify(props)}</span> */}
          //         </div>
          //       );
          //     },
          //   },
          // }}
          scopedSlots={{
            foot: (props) => {
              return (
                <div>
                  <span>自定义foot,{props.cancelText}</span>
                  {/* <span>自定义foot,{JSON.stringify(props)}</span> */}
                </div>
              );
            },
          }}
        >
          {/* 这种写法虽然也能用，但是拿不到slot-scope的值 */}
          {/* <div slot="foot" slot-scope="aaa">
            <span>自定义foot,{aaa}</span>
          </div> */}
          hello world
        </hss-modal>

        <span on-click={this.changeModal}>点击显示modal</span>
      </div>
    );
  },
  computed: {},
  created() {},
  mounted() {},
  methods: {
    changeModal() {
      this.visible = true;
    },
    visibleChange(v) {
      console.log("visibleChange", v);
    },
    cancelClick() {
      console.log("cancelClick,app组件里modal的cancel回调");
    },
    confirmClick() {
      console.log("cancelClick,app组件里modal的confirm回调");
    },
    closeClick() {
      console.log("closeClick,app组件里modal的close回调");
    },
  },
};

// src/App.vue
<template>
  <div>
    <directive-cpt></directive-cpt>
    <!-- <div v-auth="'a'">sdg</div> -->
    <div v-for="(item, index) in obj" :key="index">{{ item }},{{ index }}</div>
    <!-- <h-table></h-table> -->
    hello billd-ui
    <vue-cpt></vue-cpt>
    <vue-render-cpt></vue-render-cpt>
    <tsx-cpt></tsx-cpt>
    <jsx-cpt></jsx-cpt>
    <!-- <h-switch></h-switch>
    <h-modal
      v-model="visible"
      title="tip"
      cancelText="no"
      confirmText="ok"
      :mask="true"
      :maskClosable="false"
      @on-cancel="cancelClick"
      @on-confirm="confirmClick"
      @on-close="closeClick"
      @visible-change="visibleChange"
    >
      hello world
    </h-modal> -->
    <br />
    <span @click="changeModal">点击显示modal1</span>
    <br />
    <img src="./assets/img/author.jpg" style="width:200px" alt="" />
  </div>
</template>

<script>
// import HTable from "./components/table";

import Dashboard from '../lib/dashboard'

import VueCpt from "./components/VueCpt";
import VueRenderCpt from "./components/VueRenderCpt";
import TsxCpt from "./components/TsxCpt/index";
import JsxCpt from "./components/JsxCpt/index";
import DirectiveCpt from "./components/DirectiveCpt/index";

// import { Switch } from "../dist";
// import "../dist/switch/style/index.css";

// import { Message } from "../dist";
// import "../dist/message/style/index.css";

// import { Modal } from "../dist";
// import "../dist/modal/style/index.css";

export default {
  components: {
    Dashboard,
    VueCpt,
    VueRenderCpt,
    TsxCpt,
    JsxCpt,
    DirectiveCpt,
    // HTable,
    // HSwitch: Switch,
    // HModal: Modal,
  },
  data() {
    return {
      obj: {
        name: "hss",
        age: 22,
        sex: "男",
      },
      visible: false,
    };
  },
  computed: {},
  created() {},
  mounted() {
    // Message({
    //   content: "hello1111111111",
    //   closeAble: true,
    //   duration: 1000,
    // });
  },
  methods: {
    changeModal() {
      this.visible = true;
    },
    visibleChange(v) {
      console.log("visibleChange", v);
    },
    cancelClick() {
      console.log("cancelClick,app组件里modal的cancel回调");
    },
    confirmClick() {
      console.log("cancelClick,app组件里modal的confirm回调");
    },
    closeClick() {
      console.log("closeClick,app组件里modal的close回调");
    },
  },
};
</script>

<style scoped></style>
